### ISSUE TITLE
bot crash at start with typeError

### ISSUE THREAD

**Issue by yipcma** [nbransby/dialogue-builder-example#1]
```
TypeError: this.state.filter is not a function at TypeError: this.state.filter is not a function
    at State.stateChanged (/var/task/node_modules/dialogue-builder/dialogue-builder.js:304:32)
    at new State (/var/task/node_modules/dialogue-builder/dialogue-builder.js:301:31)
    at new Dialogue (/var/task/node_modules/dialogue-builder/dialogue-builder.js:170:22)
    at module.exports.builder.platforms (/var/task/bot.js:44:24)
    at /var/task/node_modules/claudia-bot-builder/lib/bot-builder.js:29:55
```

**Comment by nbransby** [comment]
Was due to the async logic not implemented correctly!
